language: python
python:
  - "2.7.9"
  - "2.7.13"
  - "3.6"
# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "python setup.py develop"
# command to run tests
script: py.test
